name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t dev-api:latest -f Dockerfile.dev .

      - name: Tag Docker Image
        run: docker tag dev-api:latest dokku@35.154.17.159:dev-api

      - name: Push to Dokku
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
        run: |
          ssh-agent bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY"); docker push dokku@35.154.17.159:dev-api'
