name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1.0.1
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          dokku-host: "35.154.17.159"
          ssh-port: "22"
          app-name: "dev-api"
          dockerfile: "Dockerfile.dev"
          git-push-flags: "--force"