<<<<<<< HEAD
name: prod Deployment
=======
name: Prod Deployment

>>>>>>> origin/dev

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1.0.1
        with:
<<<<<<< HEAD
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          dokku-host: "35.154.17.159"
=======
          ssh-private-key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          dokku-host: "13.200.43.28"
>>>>>>> origin/dev
          ssh-port: "22"
          app-name: "biz-api"
          git-push-flags: "--force"